sonar.projectKey=Javier-Sinuka_BSL
sonar.organization=javier-sinuka

sonar.projectName=BSL
sonar.projectVersion=1.1.0

sonar.sources=src
sonar.tests=test,mock-bpa-test

sonar.exclusions=**/*.cbor,**/*.cborseq
sonar.coverage.exclusions=test/**/*,mock-bpa-test/**/*

sonar.sourceEncoding=UTF-8
sonar.python.version=3.12